# 운영 환경(로컬 도커 테스트용) DB 설정
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://db:3306/fairplay?serverTimezone=Asia/Seoul
db.username=root
db.password=1234

# 도커 리눅스 환경에 맞는 경로 (C:/ 대신 리눅스 경로 사용)
upload.path=/usr/local/tomcat/upload