db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/fairplay?serverTimezone=Asia/Seoul
db.username=root
db.password=1234

# 이미지 업로드 경로 추가 (본인의 실제 경로로 수정하세요)
upload.path=C:/upload

# 메일 설정 (Nate)
mail.host=smtp.mail.nate.com
mail.port=465
mail.username=fairplay_@nate.com
mail.password=vpdjvmffpdl1@